### PR TITLE
king_wow

### PR DESCRIPTION
**Pull request by k1777121**

### CODE REVIEW

**Comment by ltratt** [comment]
I notice you're sometimes "king_wow" and other times "kings_wow". Which is it?

**Comment by k1777121** [comment]
I'm sorry for change the names many times, king_wow is the final group name.

**Comment by ltratt** [comment]
Thanks!

**Comment by k1777121** [comment]
Dear Dr.Tratt,

I'm sorry for my wrong operation to pull request many times.
If my operation causes you doubts, please forgive me for my fault.

Best regards,
Jian Wu

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
