### PR TITLE
group registration

### PR DESCRIPTION
**Pull request by Yathing**
all six people finished their step

### CODE REVIEW

**Comment by ltratt** [comment]
I just want to check: "lucky" is normally spelt without an "e". Is "luckey" an intentional spelling?

**Comment by Yathing** [comment]
> I just want to check: "lucky" is normally spelt without an "e". Is "luckey" an intentional spelling?

Professor Itratt:
Sorry for replying late. We just 'created' the word. If it better not to do that, we can change the group name. Thank you!

**Comment by Yathing** [comment]
> If you want to call it "luckey", you're welcome to! I just wanted to make sure it wasn't a typo. Do you want to go back to "luckey"?

we decide to be “lucky”. Thank you professor.

**Comment by Yathing** [comment]
> > If you want to call it "luckey", you're welcome to! I just wanted to make sure it wasn't a typo. Do you want to go back to "luckey"?
> 
> we decide to be “lucky”. Thank you professor.

**Comment by ltratt** [comment]
OK thanks!

**Pull request merged**
